/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.NamedObject;
import io.swagger.client.model.Relation;
import java.util.ArrayList;
import java.util.List;


/**
 * AnnotationExtension
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-07T20:15:06.627-08:00")
public class AnnotationExtension   {
  @SerializedName("filler")
  private NamedObject filler = null;

  @SerializedName("relation_chain")
  private List<Relation> relationChain = new ArrayList<Relation>();

  public AnnotationExtension filler(NamedObject filler) {
    this.filler = filler;
    return this;
  }

   /**
   * Extension interpreted as OWL expression (r1 some r2 some .. some filler).
   * @return filler
  **/
  @ApiModelProperty(example = "null", value = "Extension interpreted as OWL expression (r1 some r2 some .. some filler).")
  public NamedObject getFiller() {
    return filler;
  }

  public void setFiller(NamedObject filler) {
    this.filler = filler;
  }

  public AnnotationExtension relationChain(List<Relation> relationChain) {
    this.relationChain = relationChain;
    return this;
  }

   /**
   * Relationship type. If more than one value, interpreted as chain
   * @return relationChain
  **/
  @ApiModelProperty(example = "null", value = "Relationship type. If more than one value, interpreted as chain")
  public List<Relation> getRelationChain() {
    return relationChain;
  }

  public void setRelationChain(List<Relation> relationChain) {
    this.relationChain = relationChain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnotationExtension annotationExtension = (AnnotationExtension) o;
    return Objects.equals(this.filler, annotationExtension.filler) &&
        Objects.equals(this.relationChain, annotationExtension.relationChain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filler, relationChain);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnotationExtension {\n");
    
    sb.append("    filler: ").append(toIndentedString(filler)).append("\n");
    sb.append("    relationChain: ").append(toIndentedString(relationChain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

