/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Association;
import io.swagger.client.model.BioObject;
import io.swagger.client.model.Taxon;
import java.util.ArrayList;
import java.util.List;


/**
 * Genotype
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-07T20:15:06.627-08:00")
public class Genotype   {
  @SerializedName("label")
  private String label = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("categories")
  private List<String> categories = new ArrayList<String>();

  @SerializedName("xrefs")
  private List<String> xrefs = new ArrayList<String>();

  @SerializedName("taxon")
  private Taxon taxon = null;

  @SerializedName("variant_associations")
  private List<Association> variantAssociations = new ArrayList<Association>();

  @SerializedName("gene_associations")
  private List<Association> geneAssociations = new ArrayList<Association>();

  @SerializedName("phenotype_associations")
  private List<Association> phenotypeAssociations = new ArrayList<Association>();

  @SerializedName("disease_associations")
  private List<Association> diseaseAssociations = new ArrayList<Association>();

  public Genotype label(String label) {
    this.label = label;
    return this;
  }

   /**
   * RDFS Label
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "RDFS Label")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Genotype id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID or CURIE e.g. MGI:1201606
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "ID or CURIE e.g. MGI:1201606")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Genotype categories(List<String> categories) {
    this.categories = categories;
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getCategories() {
    return categories;
  }

  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  public Genotype xrefs(List<String> xrefs) {
    this.xrefs = xrefs;
    return this;
  }

   /**
   * Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 
   * @return xrefs
  **/
  @ApiModelProperty(example = "null", value = "Database cross-references. These are usually CURIEs, but may also be URLs. E.g. ENSEMBL:ENSG00000099940 ")
  public List<String> getXrefs() {
    return xrefs;
  }

  public void setXrefs(List<String> xrefs) {
    this.xrefs = xrefs;
  }

  public Genotype taxon(Taxon taxon) {
    this.taxon = taxon;
    return this;
  }

   /**
   * Taxon to which the object belongs
   * @return taxon
  **/
  @ApiModelProperty(example = "null", value = "Taxon to which the object belongs")
  public Taxon getTaxon() {
    return taxon;
  }

  public void setTaxon(Taxon taxon) {
    this.taxon = taxon;
  }

  public Genotype variantAssociations(List<Association> variantAssociations) {
    this.variantAssociations = variantAssociations;
    return this;
  }

   /**
   * Get variantAssociations
   * @return variantAssociations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Association> getVariantAssociations() {
    return variantAssociations;
  }

  public void setVariantAssociations(List<Association> variantAssociations) {
    this.variantAssociations = variantAssociations;
  }

  public Genotype geneAssociations(List<Association> geneAssociations) {
    this.geneAssociations = geneAssociations;
    return this;
  }

   /**
   * Get geneAssociations
   * @return geneAssociations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Association> getGeneAssociations() {
    return geneAssociations;
  }

  public void setGeneAssociations(List<Association> geneAssociations) {
    this.geneAssociations = geneAssociations;
  }

  public Genotype phenotypeAssociations(List<Association> phenotypeAssociations) {
    this.phenotypeAssociations = phenotypeAssociations;
    return this;
  }

   /**
   * Get phenotypeAssociations
   * @return phenotypeAssociations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Association> getPhenotypeAssociations() {
    return phenotypeAssociations;
  }

  public void setPhenotypeAssociations(List<Association> phenotypeAssociations) {
    this.phenotypeAssociations = phenotypeAssociations;
  }

  public Genotype diseaseAssociations(List<Association> diseaseAssociations) {
    this.diseaseAssociations = diseaseAssociations;
    return this;
  }

   /**
   * Get diseaseAssociations
   * @return diseaseAssociations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Association> getDiseaseAssociations() {
    return diseaseAssociations;
  }

  public void setDiseaseAssociations(List<Association> diseaseAssociations) {
    this.diseaseAssociations = diseaseAssociations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Genotype genotype = (Genotype) o;
    return Objects.equals(this.label, genotype.label) &&
        Objects.equals(this.id, genotype.id) &&
        Objects.equals(this.categories, genotype.categories) &&
        Objects.equals(this.xrefs, genotype.xrefs) &&
        Objects.equals(this.taxon, genotype.taxon) &&
        Objects.equals(this.variantAssociations, genotype.variantAssociations) &&
        Objects.equals(this.geneAssociations, genotype.geneAssociations) &&
        Objects.equals(this.phenotypeAssociations, genotype.phenotypeAssociations) &&
        Objects.equals(this.diseaseAssociations, genotype.diseaseAssociations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, id, categories, xrefs, taxon, variantAssociations, geneAssociations, phenotypeAssociations, diseaseAssociations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Genotype {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    xrefs: ").append(toIndentedString(xrefs)).append("\n");
    sb.append("    taxon: ").append(toIndentedString(taxon)).append("\n");
    sb.append("    variantAssociations: ").append(toIndentedString(variantAssociations)).append("\n");
    sb.append("    geneAssociations: ").append(toIndentedString(geneAssociations)).append("\n");
    sb.append("    phenotypeAssociations: ").append(toIndentedString(phenotypeAssociations)).append("\n");
    sb.append("    diseaseAssociations: ").append(toIndentedString(diseaseAssociations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

