/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AbstractPropertyValue;
import java.util.ArrayList;
import java.util.List;


/**
 * SummaryPropertyValue
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-07T20:15:06.627-08:00")
public class SummaryPropertyValue   {
  @SerializedName("val")
  private String val = null;

  @SerializedName("pred")
  private String pred = null;

  @SerializedName("xrefs")
  private List<String> xrefs = new ArrayList<String>();

  public SummaryPropertyValue val(String val) {
    this.val = val;
    return this;
  }

   /**
   * value part
   * @return val
  **/
  @ApiModelProperty(example = "null", value = "value part")
  public String getVal() {
    return val;
  }

  public void setVal(String val) {
    this.val = val;
  }

  public SummaryPropertyValue pred(String pred) {
    this.pred = pred;
    return this;
  }

   /**
   * predicate (attribute) part
   * @return pred
  **/
  @ApiModelProperty(example = "null", value = "predicate (attribute) part")
  public String getPred() {
    return pred;
  }

  public void setPred(String pred) {
    this.pred = pred;
  }

  public SummaryPropertyValue xrefs(List<String> xrefs) {
    this.xrefs = xrefs;
    return this;
  }

   /**
   * Xrefs provenance for property-value
   * @return xrefs
  **/
  @ApiModelProperty(example = "null", value = "Xrefs provenance for property-value")
  public List<String> getXrefs() {
    return xrefs;
  }

  public void setXrefs(List<String> xrefs) {
    this.xrefs = xrefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryPropertyValue summaryPropertyValue = (SummaryPropertyValue) o;
    return Objects.equals(this.val, summaryPropertyValue.val) &&
        Objects.equals(this.pred, summaryPropertyValue.pred) &&
        Objects.equals(this.xrefs, summaryPropertyValue.xrefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(val, pred, xrefs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryPropertyValue {\n");
    
    sb.append("    val: ").append(toIndentedString(val)).append("\n");
    sb.append("    pred: ").append(toIndentedString(pred)).append("\n");
    sb.append("    xrefs: ").append(toIndentedString(xrefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

