/**
 * BioLink API
 * API integration layer for linked biological objects.   __Source:__ https://github.com/monarch-initiative/biolink-api/
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IdentifierprefixesApi
 */
public class IdentifierprefixesApiTest {

    private final IdentifierprefixesApi api = new IdentifierprefixesApi();

    
    /**
     * Returns list of prefixes
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPrefixCollectionTest() throws ApiException {
        // api.getPrefixCollection();

        // TODO: test validations
    }
    
    /**
     * Returns contracted URI
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPrefixCollection_0Test() throws ApiException {
        String uri = null;
        // api.getPrefixCollection_0(uri);

        // TODO: test validations
    }
    
    /**
     * Returns expanded URI
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPrefixCollection_1Test() throws ApiException {
        String id = null;
        // api.getPrefixCollection_1(id);

        // TODO: test validations
    }
    
}
